name: CI - Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend - Lint & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint backend code
        run: |
          pip install flake8
          flake8 .

      - name: Run backend tests
        run: |
          pip install pytest
          pytest

  frontend:
    name: Frontend - Build Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Type-check frontend
        run: npm run type-check

      - name: Lint frontend code
        run: npm run lint || echo "Skipping lint if not configured"

      - name: Build frontend
        run: npm run build

  docker:
    name: Docker - Build Images
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: docker build -t gtoforge-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t gtoforge-frontend ./frontend
